# Generated by Django 4.0 on 2022-03-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.CharField(blank=True, choices=[(0, 'metals'), (1, 'softs'), (2, 'meats'), (3, 'energy'), (4, 'grains')], max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('alpha_3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('numeric', models.CharField(blank=True, max_length=6, null=True)),
                ('issuer', models.ForeignKey(blank=True, default=' ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency_country', to='economics.country')),
            ],
        ),
    ]
