# Generated by Django 4.0 on 2022-04-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('group', models.CharField(blank=True, choices=[(0, 'metals'), (1, 'softs'), (2, 'meats'), (3, 'energy'), (4, 'grains')], max_length=21, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(max_length=128)),
                ('alpha_3', models.CharField(max_length=3, primary_key=True, serialize=False)),
            ],
        ),
    ]
