# Generated by Django 4.0 on 2022-03-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('asset_class', models.CharField(choices=[(0, 'equities'), (1, 'fixed income'), (2, 'currency'), (3, 'real estate'), (4, 'commodity'), (5, 'fund'), (6, 'art'), (7, 'derivative'), (8, 'digital')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=82)),
                ('symbol', models.CharField(max_length=16)),
                ('url', models.CharField(default='', max_length=128)),
                ('daily_vol', models.FloatField()),
                ('monthly_vol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioAmounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('daily_low', models.FloatField()),
                ('daily_high', models.FloatField()),
                ('hourly_delta', models.FloatField()),
                ('daily_delta', models.FloatField()),
                ('weekly_delta', models.FloatField()),
                ('daily_vol', models.FloatField()),
                ('monthly_vol', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='watchlist', max_length=32)),
                ('assets', models.ManyToManyField(related_name='watchlist_assets', to='markets.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markets.asset')),
                ('group', models.CharField(choices=[(0, 'metals'), (1, 'softs'), (2, 'meats'), (3, 'energy'), (4, 'grains')], max_length=21)),
            ],
            bases=('markets.asset',),
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='markets.asset')),
                ('alpha_3', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('numeric', models.CharField(max_length=6)),
            ],
            bases=('markets.asset',),
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('watchlist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markets.watchlist')),
            ],
            bases=('markets.watchlist',),
        ),
    ]
