# Generated by Django 4.0 on 2022-03-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='issuer',
        ),
        migrations.AddField(
            model_name='currency',
            name='country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
