# Generated by Django 4.0 on 2022-03-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0002_remove_currency_issuer_currency_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
