# Generated by Django 4.0 on 2022-03-27 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0003_alter_currency_country_code_alter_currency_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='numeric',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='symbol',
        ),
    ]
