# Generated by Django 4.0 on 2022-03-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0003_remove_country_currencies_country_currencies'),
        ('markets', '0004_remove_currency_numeric_remove_currency_symbol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country_code',
        ),
        migrations.AddField(
            model_name='currency',
            name='countries',
            field=models.ManyToManyField(related_name='currency_countries', to='economics.Country'),
        ),
    ]
