# Generated by Django 4.0 on 2022-03-27 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0005_remove_currency_country_code_currency_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='countries',
        ),
    ]
