# Generated by Django 4.0 on 2022-03-27 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crypto', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('signup_location', models.CharField(max_length=64)),
                ('signup_ip', models.CharField(max_length=45)),
                ('exchanges', models.ManyToManyField(to='crypto.CryptoExchange')),
                ('friends', models.ManyToManyField(to='website.Account')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='auth.user')),
                ('watchlists', models.ManyToManyField(to='crypto.Watchlist')),
            ],
        ),
    ]
