# Generated by Django 4.0 on 2022-03-26 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('alpha_3', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=64)),
                ('numeric', models.IntegerField()),
                ('gdp', models.FloatField()),
                ('gdp_ppp', models.FloatField()),
                ('population', models.IntegerField(validators=[django.core.validators.MaxValueValidator(30000000000)])),
            ],
        ),
    ]
