# Generated by Django 4.0 on 2022-03-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('currencies', models.CharField(max_length=32)),
            ],
        ),
    ]
