# Generated by Django 4.0 on 2022-03-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('economics', '0001_initial'),
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='country_currencies', to='markets.Currency'),
        ),
    ]
