# Generated by Django 4.0 on 2022-03-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0004_remove_currency_numeric_remove_currency_symbol'),
        ('economics', '0002_alter_country_currencies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='currencies',
        ),
        migrations.AddField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='country_currencies', to='markets.Currency'),
        ),
    ]
