# Generated by Django 4.0 on 2022-03-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0006_remove_currency_countries'),
        ('economics', '0003_remove_country_currencies_country_currencies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='currencies',
            field=models.ManyToManyField(related_name='country_currencies', related_query_name='currency_country', to='markets.Currency'),
        ),
    ]
