# Generated by Django 4.0 on 2022-03-26 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markets.asset')),
                ('url', models.CharField(max_length=128)),
            ],
            bases=('markets.asset',),
        ),
        migrations.CreateModel(
            name='CryptoExchange',
            fields=[
                ('market_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='markets.market')),
                ('crypto_only', models.BooleanField()),
                ('kyc', models.BooleanField()),
                ('grade', models.CharField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'NA')], max_length=3)),
            ],
            bases=('markets.market',),
        ),
        migrations.CreateModel(
            name='NFTCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Cryptocurrency',
            fields=[
                ('cryptoasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crypto.cryptoasset')),
                ('hash_algorithm', models.CharField(max_length=64)),
                ('proof_type', models.CharField(max_length=32)),
                ('total_coins_mined', models.FloatField()),
                ('circ_supply', models.FloatField()),
                ('max_supply', models.FloatField()),
                ('block_reward', models.FloatField()),
                ('used_in_defi', models.BooleanField()),
                ('used_in_nft', models.BooleanField()),
            ],
            bases=('crypto.cryptoasset',),
        ),
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('cryptoasset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crypto.cryptoasset')),
                ('floor_price', models.FloatField()),
                ('quote_curr', models.CharField(max_length=16)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crypto.nftcollection')),
            ],
            bases=('crypto.cryptoasset',),
        ),
    ]
