# Generated by Django 4.0 on 2022-03-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
