# Generated by Django 4.0 on 2022-03-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_cryptocurrency_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticker',
        ),
    ]
