# Generated by Django 4.0 on 2022-03-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economics', '0005_alter_country_currencies'),
        ('markets', '0006_remove_currency_countries'),
        ('crypto', '0004_delete_ticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoexchange',
            name='crypto_only',
        ),
        migrations.AlterField(
            model_name='cryptoexchange',
            name='countries',
            field=models.ManyToManyField(related_name='exchange_countries', to='economics.Country'),
        ),
        migrations.AlterField(
            model_name='cryptoexchange',
            name='currencies',
            field=models.ManyToManyField(related_name='exchange_currencies', to='markets.Currency'),
        ),
        migrations.AlterField(
            model_name='cryptoexchange',
            name='grade',
            field=models.CharField(blank=True, choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'NA')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='cryptoexchange',
            name='tickers',
            field=models.ManyToManyField(related_name='exchange_tickers', to='crypto.Cryptocurrency'),
        ),
        migrations.AlterField(
            model_name='cryptoexchange',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
