# Generated by Django 4.0 on 2022-04-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0006_alter_cryptoexchange_daily_vol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoFiatTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=16)),
                ('quote', models.CharField(max_length=3)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('daily_vol', models.FloatField(blank=True, null=True)),
                ('daily_low', models.FloatField(blank=True, null=True)),
                ('daily_high', models.FloatField(blank=True, null=True)),
                ('daily_delta', models.FloatField(blank=True, null=True)),
                ('mkt_cap', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=16)),
                ('quote', models.CharField(max_length=16)),
                ('bid', models.FloatField(blank=True, null=True)),
                ('ask', models.FloatField(blank=True, null=True)),
                ('daily_vol', models.FloatField(blank=True, null=True)),
                ('daily_low', models.FloatField(blank=True, null=True)),
                ('daily_high', models.FloatField(blank=True, null=True)),
                ('daily_delta', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
